version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: "your_database_name"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://your_username:your_password@postgres:5432/your_database_name"
      DISCORD_TOKEN: "your_discord_bot_token"
