version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/bot
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    depends_on:
      - postgres
    ports:
      - "5432:5432"  # Mapeie a porta do contêiner para a porta do host, se necessário
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/api
    networks:
      - app-network

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
